version: "3"
services:
  empowerdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: empower
      POSTGRES_PASSWORD: empowerpass
      POSTGRES_DB: empowerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: misstipo/api-gateway:latest
    ports:
      - "8000:8000"

  user-profile:
    build:
      context: ../user-profile-service
      dockerfile: Dockerfile
    image: misstipo/user-profile:latest
    ports:
      - "8001:8001"
    depends_on:
      - empowerdb
    environment:
      - DATABASE_URL=postgresql://empower:empowerpass@empowerdb:5432/empowerdb

  organization-profile:
    build:
      context: ../organization-profile-service
      dockerfile: Dockerfile
    image: misstipo/organization-profile:latest
    ports:
      - "8002:8002"

  telephony-integration:
    build:
      context: ../telephony-integration-service
      dockerfile: Dockerfile
    image: misstipo/telephony-integration:latest
    ports:
      - "8003:8003"

  resource-matching-service:
    build:
      context: ../resource-matching-service
      dockerfile: Dockerfile
    image: misstipo/resource-matching-service:latest
    ports:
      - "8004:8004"
    depends_on:
      - empowerdb
    environment:
      - DATABASE_URL=postgresql://empower:empowerpass@empowerdb:5432/empowerdb

  geospatial-mapping-service:
    build:
      context: ../geospatial-mapping-service
      dockerfile: Dockerfile
    image: misstipo/geospatial-mapping-service:latest
    ports:
      - "8005:8005"
    depends_on:
      - empowerdb
    environment:
      - DATABASE_URL=postgresql://empower:empowerpass@empowerdb:5432/empowerdb

  inclusivity-index-service:
    build:
      context: ../inclusivity-index-service
      dockerfile: Dockerfile
    image: misstipo/inclusivity-index:latest
    ports:
      - "8006:8006"
    depends_on:
      - empowerdb
      - redis
    environment:
      - DATABASE_URL=postgresql://empower:empowerpass@empowerdb:5432/empowerdb
      - CELERY_BROKER_URL=redis://redis:6379/0

  inclusivity-worker:
    build:
      context: ../inclusivity-index-service
      dockerfile: Dockerfile.worker  # or use the same Dockerfile if API & worker are in one image
    image: misstipo/inclusivity-worker:latest
    depends_on:
      - empowerdb
      - redis
    environment:
      - DATABASE_URL=postgresql://empower:empowerpass@empowerdb:5432/empowerdb
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
