version: "3"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: empower
      POSTGRES_PASSWORD: empowerpass
      POSTGRES_DB: empowerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

version: "3"
services:
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: misstipo/api-gateway:latest
    ports:
      - "8000:8000"

  user-profile:
    build:
      context: ../user-profile-service
      dockerfile: Dockerfile
    image: misstipo/user-profile:latest
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://empower:empowerpass@postgres:5432/empowerdb

  organization-profile:
    build:
      context: ../organization-profile-service
      dockerfile: Dockerfile
    image: misstipo/organization-profile:latest
    ports:
      - "8002:8002"
