version: "3"
services:
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: misstipo/api-gateway:latest
    ports:
      - "8000:8000"

  user-profile:
    build:
      context: ../user-profile-service
      dockerfile: Dockerfile
    image: misstipo/user-profile:latest
    ports:
      - "8001:8001"
