FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .  
RUN pip install --no-cache-dir -r requirements.txt
COPY app/ ./app/
COPY workers/ ./workers/
CMD ["celery", "-A", "workers.tasks", "worker", "--loglevel=info"]

