name: API Gateway CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "services/api-gateway/**"
  pull_request:
    branches: [ main ]
    paths:
      - "services/api-gateway/**"

jobs:
  test:
    name: Run API Gateway Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api-gateway
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python3 -m pytest

  build_and_deploy:
    name: Build, Push, and Deploy API Gateway
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: services/docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build and Push API Gateway Image with Docker Compose
        run: |
          docker compose build api-gateway
          docker compose push api-gateway

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.24.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin

      - name: Generate Kubernetes Manifests
        run: |
          mkdir -p k8s
          # Generate manifests from docker-compose.yml located in the services folder root.
          kompose convert -f docker-compose.yml -o ../k8s/

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: empowerlink-nexus

      - name: Debug gcloud Auth
        run: gcloud auth list

      - name: Set active account from JSON key
        run: |
          ACCOUNT=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.client_email')
          gcloud config set account $ACCOUNT



      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials empowerlink-cluster --zone us-central1-a --project empowerlink-nexus

      - name: Configure Kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          cat $HOME/.kube/config

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q

      - name: Delete existing api-gateway deployment (if any)
        run: |
          kubectl delete deployment,service -l app=api-gateway --ignore-not-found=true --grace-period=0 --force
          kubectl delete service api-gateway-service --ignore-not-found=true
          kubectl wait --for=delete deployment/api-gateway --timeout=60s || true

      - name: Deploy to Kubernetes
        run: |
          kubectl delete -R -f ../k8s/ --ignore-not-found=true
          kubectl wait --for=delete deployment/api-gateway --timeout=60s || true
          kubectl wait --for=delete service/api-gateway --timeout=60s || true
          kubectl wait --for=delete service/api-gateway-service --timeout=60s || true
          kubectl create -R -f ../k8s/

