name: Telephony Integration CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "services/telephony-integration-service/**"
  pull_request:
    branches: [ main ]
    paths:
      - "services/telephony-integration-service/**"

jobs:
  test:
    name: Run Telephony Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/telephony-integration-service
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python3 -m pytest

  build_and_deploy:
    name: Build, Push, and Deploy Telephony Integration
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: services/docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Telephony Image with Docker Compose
        run: |
          docker compose build telephony-integration
          docker compose push telephony-integration

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.24.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin

      - name: Generate Kubernetes Manifests
        run: |
          mkdir -p k8s
          kompose convert -f docker-compose.yml -o ../k8s/

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set Kubernetes Context
        run: doctl kubernetes cluster kubeconfig save k8s-empowerlink-nexus


      - name: Use DO cluster context
        run: kubectl config use-context do-tor1-k8s-empowerlink-nexus

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: '${{ secrets.GCP_SA_KEY }}'
      #
      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: empowerlink-nexus
      #
      # - name: Set active account from JSON key
      #   run: |
      #     ACCOUNT=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.client_email')
      #     gcloud config set account $ACCOUNT
      #
      # - name: Get GKE Credentials
      #   run: |
      #     gcloud container clusters get-credentials empowerlink-cluster --zone us-central1-a --project empowerlink-nexus
      #
      # - name: Install gke-gcloud-auth-plugin
      #   run: |
      #     gcloud components install gke-gcloud-auth-plugin -q

      - name: Ensure full cleanup of telephony-integration
        run: |
          kubectl delete deployment telephony-integration --ignore-not-found=true --grace-period=0 --force
          kubectl delete rs -l app=telephony-integration --ignore-not-found=true
          kubectl delete pods -l app=telephony-integration --ignore-not-found=true
          kubectl delete service telephony-integration --ignore-not-found=true
          kubectl delete service telephony-integration-service --ignore-not-found=true

      - name: List k8s files for debugging
        run: |
          echo "Listing k8s files..."
          ls -l ../k8s/

      - name: Deploy to Kubernetes
        run: |
          kubectl create -f ../k8s/telephony-integration-deployment.yaml
          kubectl create -f ../k8s/telephony-integration-service.yaml

